[project]
name = "voice-changer-server"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "onnx>=1.20.1",
    "onnxruntime>=1.24.1",
    "onnxsim>=0.4.36",
    "torch>=2.10.0",
]
